# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  aoc-2015:
    name: python
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install the project
      run: uv sync --all-extras

    - name: Ruff it
      run: uv run ruff check

    - name: Test it
      run: |
        for i in {1..5}; do ./get_input.sh $i; done
        cd test
        uv run pytest
      env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}